### ISSUE TITLE
请问这个是否已经失效

### ISSUE THREAD

**Issue by Roc136** [blogimg/WakeLeanCloud#3]
运行时好时坏的，而且即使运行成功也不能唤醒leancloud
![image](https://user-images.githubusercontent.com/57868577/85940394-a7ade300-b94e-11ea-9bc1-4d852d429f8a.png)
![image](https://user-images.githubusercontent.com/57868577/85940737-cca35580-b950-11ea-8625-4cfe2df7f7d1.png)

**Comment by GamerNoTitle** [comment]
你也得点进去没运行成功的那些看看是什么原因呀……
理论上来说，只要Leancloud还保持着只要有人访问就不休眠的设定，这个东西是可以一直用下去的

**Comment by Roc136** [comment]
> 你也得点进去没运行成功的那些看看是什么原因呀……
> 理论上来说，只要Leancloud还保持着只要有人访问就不休眠的设定，这个东西是可以一直用下去的

谢谢，已经解决了，忘记关issue了，抱歉
